<?php

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-01'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><h2>Herzlichen Glückwunsch,</h2><p>Sie haben eine gute Wahl getroffen und MERCONIS in Ihr Modul-Verzeichnis kopiert.</p><p class="shopHint"><strong>Hinweis:</strong> Bitte folgen Sie nun den Installationsanweisungen, deaktivieren Sie den internen Contao-Cache während der Installation und führen Sie keine anderen Backend-Aktivitäten durch. Bis zum vollständigen Abschluss der MERCONIS-Installation arbeiten einige Contao-Grundfunktionen möglicherweise fehlerhaft, da noch nicht alle relevanten Einstellungen vorgenommen wurden.</p><p>Der MERCONIS-Installer wird in Ihrem bestehenden Contao-Projekt vollautomatisch alle benötigten Seiten, Artikel, Module und Formulare anlegen und Demo-Daten einfügen. Für weitere Informationen verweisen wir auf das Online-Handbuch.</p><p><a href="%s">Installation beginnen</a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-02'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>Bitte führen Sie nun das <a href="%s">Contao-Install-Tool</a> aus.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-03'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>MERCONIS ist noch nicht vollständig eingerichtet. Klicken Sie <a href="%s">hier</a>, um die automatische Einrichtung durchzuführen.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-04'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>Sie haben in Contao noch keine Seite vom Typ "Startpunkt einer Webseite" eingerichtet. Bitte stellen Sie sicher, dass eine solche Seite existiert, bevor Sie die Installation des Shops durchführen.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-05'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>Sie haben in Contao noch kein Theme angelegt. Bitte legen Sie ein Theme an, bevor Sie die Installation des Shops durchführen, da die Shop-Module einem Theme zugeordnet werden müssen.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-06'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>MERCONIS ist noch nicht vollständig eingerichtet. Bitte wählen Sie, mit welchem Theme Sie MERCONIS einrichten möchten.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-07'] = 'Mit gewähltem Theme einrichten';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-08'] = 'Live-Vorschau';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-09'] = 'Es stehen keine Themes zur Verfügung, bitte kontaktieren Sie den MERCONIS Support, um das Problem zu beheben.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-10'] = 'Dieses Theme ist nur kompatibel mit Contao %s';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-11'] = 'Dieses Theme ist nur kompatibel mit MERCONIS %s';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-12'] = 'Das von Ihnen gewählte Theme kann nicht eingerichtet werden. Bitte kontaktieren Sie den MERCONIS Support, um das Problem zu beheben, oder wählen Sie ein anderes Theme.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-13'] = 'Bitte wählen Sie ein Theme';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-14'] = 'Heruntergeladene Themes';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-15'] = 'Online Theme Repository';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-16'] = 'Der direkte Zugriff auf das Online-Theme-Repository ist aktuell nicht möglich%s. Sollten Sie ein anderes Theme als das bereits mitgelieferte Theme "Basic" verwenden wollen, besuchen Sie bitte zunächst <a target="_blank" href="http://themes.merconis.com">themes.merconis.com</a>, laden das gewünschte Theme dort herunter und setzen danach die Installation fort.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-17'] = 'CURL-Erweiterung nicht verfügbar';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-18'] = 'Keine Daten empfangen';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-19'] = 'Der Abruf eines Themes aus dem Online Theme Repository dauert üblicherweise nur einige Sekunden, kann aber abhängig von der Internetverbindung unter Umständen bis zu einer Minute dauern.';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage07'] = '<h2>MERCONIS %s ist vollständig eingerichtet!</h2><p>Sie können den Shop im Frontend <a href="%s" target="_blank">HIER</a> anschauen.</p><p>Sie können nun mit der individuellen Anpassung Ihres Shops beginnen. Wir empfehlen Ihnen, einen Blick in die entsprechende Checkliste im Handbuch zu werfen.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage08'] = '<h2>MERCONIS %s ist vollständig eingerichtet!</h2>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage09'] = '<h2>Die von Ihnen eingesetzte Contao-Version ist nicht kompatibel mit dieser MERCONIS-Version.</h2>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage10'] = '<p class="shopHint">Wichtiger Hinweis: Der MERCONIS-Installer hat eine mehrsprachige Seitenstruktur angelegt. Damit die Mehrsprachigkeit richtig verarbeitet wird und MERCONIS korrekt dargestellt werden kann, muss die Seite "MERCONIS - Root page (main language)" als Sprachen-Fallback gekennzeichnet werden. Diese Kennzeichnung konnte vom Installer nicht automatisch durchgeführt werden, da möglicherweise ein Konflikt mit einer bereits existierenden Root-Seite vorlag. Bitte nehmen Sie die entsprechende Einstellung daher bei Bedarf manuell vor.</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage11'] = '<p>Die vorliegende Programmversion weicht vom aktuellen Einrichtungszustand ab. Dies ist in Ordnung, wenn Sie gerade für ein Update die Programmdateien einer neuen MERCONIS-Version eingespielt haben.</p><p><strong>Ihr Einrichtungszustand entspricht Version %s<br />Ihre Programmversion ist %s</strong></p><p class="bottomButton"><a href="%s"><button type="button">Update beginnen</button></a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage12'] = 'Anweisungen';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage13'] = '<p><strong>Das Update umfasst mehrere Versionssprünge, die einzeln abgearbeitet werden müssen. Bitte halten Sie sich genau an die vorgegebene Reihenfolge.</strong></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage14'] = '<p class="bottomButton"><a href="%s" onclick="return confirm(\'Sind sie sicher?\');"><button type="button">Update als erledigt kennzeichnen</button></a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage15'] = '<h2 class="merconisUpdaterHeadline">MERCONIS UPDATE HELPER</h2>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage16'] = '<p>Folgen Sie nun bitte den verlinkten Anweisungen. Klicken Sie <a href="%s">hier</a>, um das Contao-Install-Tool aufzurufen, wenn Sie in den Anweisungen dazu aufgefordert werden.</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage17'] = '<p>Ihre zuletzt installierte Version konnte nicht eindeutig ermittelt werden. Bitte wählen Sie, welche Version Sie vor dem Einspielen der neuen Programmdateien installiert hatten.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage18'] = 'Konvertierungsroutine ausführen';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage19'] = 'Konvertierung wurde durchgeführt';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage20'] = 'Konvertierung noch nicht möglich';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage21'] = '<span class="updateLessImportantNote">Für diesen Versionssprung ist nichts zu tun.</span>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage22'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p class="shopHint">In Ihrem Projekt ist die automatische Installation nicht möglich. Entweder liegt eine abgebrochene oder unvollständig deinstallierte MERCONIS-Installation vor oder andere Umgebungsbedingungen verhindern den Einsatz des Installers.</p><p>Bitte kontaktieren Sie den <strong>MERCONIS techSupport</strong> telefonisch oder per E-Mail, um das Problem zu beheben und/oder Unterstützung bei der MERCONIS-Inbetriebnahme ohne den automatischen Installer zu bekommen. Die Kontaktdaten des <strong>MERCONIS techSupport</strong> finden Sie auf <a href="http://www.merconis.com" target="_blank">www.merconis.com</a></p><p><strong>HINWEIS:</strong> Diese Meldung wird Ihnen auch bei einer eigentlich korrekten und vollständigen MERCONIS-Installation angezeigt, falls in Ihrer localconfig.php der Eintrag "ls_shop_installedCompletely" entfernt wurde bzw. nicht auf "true" steht, was z. B. durch das Zurückspielen einer alten Version Ihrer localconfig.php der Fall sein kann.</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['updateErrors']['currentVersionSituationInvalid'] = '<p class="shopHint">Die ermittelten Versionsnummern für den Einrichtungszustand und die vorliegenden Programmdateien sind fehlerhaft. Dieser Fehler tritt z. B. auf, wenn der Einrichtungszustand einer höheren Version entspricht als die aktuell vorhandenen Dateien. Dies würde eine Herabstufung der MERCONIS-Version bedeuten und wird vom UPDATE HELPER nicht unterstützt. Falls Sie dennoch eine Herabstufung durchführen wollen, führen Sie die notwendigen änderungen (Einstellungen, Module etc.) bitte nach eigenem Ermessen durch.</p>';