<?php
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-01'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><h2>Congratulations! </h2><p>You have made a good choice by copying MERCONIS to your module directory.</p><p class="shopHint"><strong>Note:</strong> Please follow the installation instructions, disable the internal Contao cache and do NOT run additional back-end activities. Until completion of the MERCONIS installation routine, it might be possible that some Contao basic functions do not work the way they should since not all relevant settings have been made yet.</p><p>The MERCONIS installer will insert all required pages, articles, modules and forms as well as sample data into your existing Contao project. For further information please take a look at the online documentation.</p><p><a href="%s">Begin installation</a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-02'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><p>Please run the <a href="%s">Contao Installation Tool</a> now.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-03'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><p>MERCONIS has not been installed completely yet. Click <a href="%s">here</a> to run the automatic installation routine.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-04'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><p>You have not defined a page of the type "Website root" yet. Please make sure such a page exists before you run the shop installation routine.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-05'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><p>You have not defined a theme in Contao yet. Please define a theme before you run the shop installation routine because the shop modules must be allocated a theme.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-06'] = '<h2 class="merconisInstallerHeadline">MERCONIS-INSTALLER</h2><p>MERCONIS has not been installed completely yet. Please choose the theme to use for installation.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-07'] = 'Install with selected theme';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-08'] = 'Live preview';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-09'] = 'No themes are available. Please contact the MERCONIS support in order to fix this issue.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-10'] = 'This theme is only compatible with Contao %s';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-11'] = 'This theme is only compatible with MERCONIS %s';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-12'] = 'The theme you selected can not be installed. Please contact the MERCONIS support in order to fix this issue or choose another theme.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-13'] = 'Please choose a theme';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-14'] = 'Downloaded themes';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-15'] = 'Online Theme Repository';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-16'] = 'Direct access to the online theme repository isn\'t possible at the moment%s. If you want to use another theme instead of the included theme "Basic", please visit <a target="_blank" href="http://themes.merconis.com">themes.merconis.com</a>, download the favored theme from there and continue installation afterwards.';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-17'] = 'CURL extension not available';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-18'] = 'No data received';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage01-19'] = 'Retrieving a theme from the online theme repository usually only takes a few seconds. Depending on the internet connection it may take up to 1 minute.';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage07'] = '<h2>MERCONIS %s has been set up completely!</h2><p>You can take a look at your shop in the front end <a href="%s" target="_blank">HERE</a> .</p><p>You can now start with your individual shop configuration. We recommend you to read the corresponding checklist in the manual.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage08'] = '<h2>MERCONIS %s has been set up completely!</h2>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage09'] = '<h2>Your Contao version is not compatible with this version of MERCONIS.</h2>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage10'] = '<p class="shopHint">Important note: The MERCONIS installer has generated a multilingual page structure. To enable correct processing of multilingualism and correct presentation of MERCONIS, the page  "MERCONIS - Root page (main language)" must be marked language fallback. The installer could not mark the language fallback automatically since there might have been a conflict with an already existing root page. Please make the relevant setting manually, if required.</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage11'] = '<p>The programm version on hand deviates from the current installation state. This is okay if you have only just loaded the program files of a new MERCONIS version for an update.</p><p><strong>Your installation state corresponds to version %s<br />Your program version is %s</strong></p><p class="bottomButton"><a href="%s"><button type="button">Start update</button></a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage12'] = 'Instructions';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage13'] = '<p><strong>The update comprises several version updates which must be worked off separately. Please strictly adhere to the given order.</strong></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage14'] = '<p class="bottomButton"><a href="%s" onclick="return confirm(\'Are you sure?\');"><button type="button">Mark update as completed</button></a></p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage15'] = '<h2 class="merconisUpdaterHeadline">MERCONIS UPDATE HELPER</h2>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage16'] = '<p>Please follow the instructions in the link now. Click <a href="%s">here</a> to call the Contao install tool if the instructions prompt you to do this</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage17'] = '<p>Your last installed version could not be clearly identified. Please select the version that you had installed on your system before you loaded the new program files.</p>';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage18'] = 'Run conversion routine';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage19'] = 'Conversion completed';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage20'] = 'Conversion not possible yet';
$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage21'] = '<span class="updateLessImportantNote">Nothing to do for this update step</span>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['installToolMessage22'] = '<h2 class="merconisInstallerHeadline">MERCONIS INSTALLER</h2><p class="shopHint">The automatic installation is not possible in your project. There must be either an aborted or incompletely uninstalled MERCONIS installation or other environmental conditions make the use of the installer impossible.</p><p>Please contact the <strong>MERCONIS techSupport</strong> in order to solve the problem and/or to get help with setting up MERCONIS without the automatic installer. You can find the contact information of the <strong>MERCONIS techSupport</strong> on the MERCONIS website <a href="http://www.merconis.com" target="_blank">(www.merconis.com)</a>.</p><p><strong>HINT:</strong> You can also see this message in a complete and correctly set up MERCONIS installation if the entry "ls_shop_installedCompletely" has been removed from your localconfig.php or is not set to "true", which might be the case if you restored an old version of your localconfig.php from a backup.</p>';

$GLOBALS['TL_LANG']['MSC']['ls_shop']['systemMessages']['updateErrors']['currentVersionSituationInvalid'] = '<p class="shopHint">The identified version numbers for the current installation state and the existing program files are faulty. This error occurs e.g. if the installation state corresponds to a higher version than the version of the currently existing program files. This would mean downgrading your MERCONIS version which is not supported by the UPDATE HELPER. If you actually want to perform this downgrade, please arrange the necessary changes (settings, modules etc.) as you see fit.</p>';