<?php

	/*
	 * Fields
	 */
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_activateFilter']			= array('Activate product filter', 'If you want to use the product filter, please activate it by selecting this option. Note: If you don\'t use the frontend module "filter form" and therefore filtering isn\'t possible, we advise you to completely deactivate the product filter here in order to optimize system performance.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterInStandardProductlist'] = array('Use filter in standard product overview', 'Select this option if you want to use the product filter in product lists generated by the frontend module "product overview" (e.g. the typical category view)');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterMatchEstimates'] = array('Determine estimated number of matches');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_matchEstimatesMaxNumProducts'] = array('Product limit for estimated matches', 'Depending on the performance of your server it might be useful to limit the number of products in your product list for which the estimated number of matches will be determined.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_matchEstimatesMaxFilterValues'] = array('Filter value limit for estimated matches', 'Depending on the performance of your server it might be useful to limit the number of filter values in your filter form for which the estimated number of matches will be determined.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_useFilterInProductDetails'] = array('Use filter in product details', 'Select this option if you want to use the filter in the product details which enables variant filtering.');
	$GLOBALS['TL_LANG']['tl_layout']['ls_shop_hideFilterFormInProductDetails'] = array('Hide filter form in product details');

	/*
	 * Legends
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsShopFilter_legend']   = 'MERCONIS: Filter settings';
	$GLOBALS['TL_LANG']['tl_layout']['lsShopJsComponents_legend']   = 'MERCONIS: Javascript plug-Ins';
